config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root to: 'dashboard#index'
  
  resources :restaurants do
    resources :menus, except: :index
    get 'update_menus', to: 'restaurants#update_menus'
  end
  
  resources :dashboard, only: :index

  resources :comments, only: :create

  resource :votes, only: [:show, :create, :destroy]

  resources :votes do
    resources :comments, only: [:new, :edit, :create, :update]
  end

  resources :settings, only: [:index, :create]

  resource :group, only: [:show, :update] do
    post :add_user
    put :update_restaurants
  end

  resources :balances, only: :index
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    Restaurant.connection.execute "select setseed(#{seed})"
    @restaurants = current_group.restaurants.order 'random()'
    @comments = Comment.where("created_at >= ? and group_id = ? and vote_id IS NULL", Time.zone.now.beginning_of_day, current_group.id).order(created_at: :asc)
    @comment = Comment.new
    @top_5 = top_for_date Date.today
    @last_3_days = last_3_days
  end

  private

  def seed
    today = Date.today + 1
    Random.new(today.day * today.month * today.year).rand - 1
  end

  def top_for_date(date, top = 5)
    ActiveRecord::Base.connection.exec_query("
      SELECT restaurants.name, COUNT(votes) as res_votes
      FROM restaurants
      LEFT JOIN votes as votes ON votes.restaurant_id = restaurants.id
      WHERE votes.date = '#{date}'
      AND votes.group_id = #{current_group.id}
      GROUP BY restaurants.id
      ORDER BY res_votes DESC
      LIMIT #{top}").rows
  end

  def last_3_days
    top = []
    date = Date.today - 1
    stop = date - 2
    while date >= stop
      if date.wday == 6 || date.wday == 0
        stop -= 1
      else
        top << {date: date, restaurant: top_for_date(date, 1).first.try(:first)}
      end
      date -= 1
    end
    top
  end
end

app/views/dashboard/_balance_table.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title
      - if current_group.balance_table_link.empty?
        Balance table
      - else
        = link_to 'Balance table', current_group.balance_table_link, target: '_blank'
  %table.table.table-hover#balance-table
    %tr
      %td.text-center
        Loading...

app/views/dashboard/_comment.html.haml
%li.list-group-item
  .row
    .col-md-8
      %h4.list-group-item-heading
        = comment.user.username
    .col-md-4.text-right
      = comment.created_at.in_time_zone('CET').strftime('%k:%M')
  %p.list-group-item-text.comment
    = comment.text

app/views/dashboard/_comments.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title
      Comments
  %ul.list-group.fixed-height#comments
    = render partial: 'comment', collection: @comments
  .panel-footer
    = form_for @comment, url: {controller: 'comments',action: 'create'} do |f|
      .form-group
        = f.text_area :text, placeholder: 'Write a comment...', required: true, class: 'form-control'
      = f.submit "Leave a comment", class: 'btn btn-success'

app/views/dashboard/_last_3_days.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title
      Last 3 days
  %table.table.table-hover
    - @last_3_days.each do |day|
      %tr
        %td.text-left
          = day[:restaurant]
        %td.text-right
          = day[:date].strftime("%e.%-m.%Y")
        

app/views/dashboard/_restaurant.html.haml
.col-md-4
  .panel.panel-default
    .panel-heading
      %h3.panel-title
        %a.collapse-link{role: 'button', data: {toggle: 'collapse'}, href: "#restaurant_#{restaurant.id}", aria: {expanded: !current_user.collapsed?, controls: "#restaurant_#{restaurant.id}"}, class: ('collapsed' if current_user.collapsed?)}
        = link_to restaurant.name, restaurant_path(restaurant)
        - if restaurant.menu_link.present?
          = link_to restaurant.menu_link, target: '_blank' do
            %i.glyphicon.glyphicon-list-alt
        - unless restaurant.todays_images.empty?
          %a{target: '_blank', href: restaurant.todays_images[0].url}
            %i.glyphicon.glyphicon-file
        = link_to new_restaurant_menu_path(restaurant) do
          %i.glyphicon.glyphicon-plus
        - unless restaurant.telephone_number.empty?
          %span.phone
            = link_to restaurant.telephone_number, "tel:#{restaurant.telephone_number}"
    .panel-collapse.collapse{id: "restaurant_#{restaurant.id}", class: ('in' unless current_user.collapsed?)}
      .fixed-height
        %table.table.table-hover
          - if restaurant.todays_menus.empty?
            %tr
              %td.text-center
                - if restaurant.menu_link.present?
                  = link_to restaurant.menu_link, target: '_blank' do
                    %i.glyphicon.glyphicon-list-alt
                    Menu
                - else
                  No data
          - else
            - restaurant.todays_menus.each_with_index do |menu, i|
              %tr{class: ('info' if menu.regular?)}
                %td.col-md-1.text-left= i + 1
                %td.col-md-9.text-left= menu.description
                %td.col-md-1.text-right
                  = "#{menu.price}€" if menu.price.present?
                %td.col-md-1.text-right
                  - unless current_user.voted_menu?(menu.id)
                    = link_to 'V', votes_path(menu_id: menu), method: :post, class: 'btn btn-success btn-xs', title: 'Vote'
                  - else
                    = link_to 'U', votes_path, method: :delete, class: 'btn btn-danger btn-xs',  title: 'Unvote', data: {confirm: 'Are you sure?'}
    .panel-footer
      .row
        .col-md-6
          - unless current_user.voted?(restaurant.id)
            = link_to 'Vote', votes_path(restaurant_id: restaurant), method: :post, class: 'btn btn-success'
          - else
            = link_to 'Unvote', votes_path, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'}
            - if current_user.my_vote.comment.present?
              = link_to edit_vote_comment_path(vote_id: current_user.my_vote.comment.vote_id, id: current_user.my_vote.comment.id), class: 'btn btn-success' do
                %i.glyphicon.glyphicon-comment
            - else
              = link_to new_vote_comment_path(current_user.my_vote), class: 'btn btn-success' do
                %i.glyphicon.glyphicon-comment

        .col-md-6.text-right
          %h5
            No. of votes
            %span.badge
              = restaurant.today_votes_number(current_user)
        .col-md-12.text-right
          - restaurant.voters(current_user).each do |voter|
            %span.badge{data: {toggle: 'tooltip', placement: 'bottom'}, title: voter.username}
              = voter.initials

app/views/dashboard/_statisctics.html.haml
= javascript_include_tag '//www.google.com/jsapi', 'chartkick'
.panel.panel-default
  .panel-heading
    %h3.panel-title
      Top 5
  .panel-body
    = pie_chart @top_5, height: '200px'

app/views/dashboard/_top_5.html.haml
= javascript_include_tag '//www.google.com/jsapi', 'chartkick'
.panel.panel-default
  .panel-heading
    %h3.panel-title
      Top 5
  .panel-body
    = pie_chart @top_5, height: '200px'

app/views/dashboard/index.html.haml
.col-md-9
  - if @restaurants.empty?
    .text-center
      = link_to 'Add restaurants', group_path, class: 'btn btn-success'
  - @restaurants.each_slice(3) do |restaurants|
    .row.row-eq-height.restaurants
      = render partial: 'restaurant', collection: restaurants
.col-md-3
  .row
    .col-md-12
      = render partial: 'top_5'
    .col-md-12
      = render partial: 'comments'
    .col-md-12
      = render partial: 'balance_table' if current_group.balance_table?
    .col-md-12
      = render partial: 'last_3_days'