config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root to: 'dashboard#index'
  
  resources :restaurants do
    resources :menus, except: :index
    get 'update_menus', to: 'restaurants#update_menus'
  end
  
  resources :dashboard, only: :index

  resources :comments, only: :create

  resource :votes, only: [:show, :create, :destroy]

  resources :votes do
    resources :comments, only: [:new, :edit, :create, :update]
  end

  resources :settings, only: [:index, :create]

  resource :group, only: [:show, :update] do
    post :add_user
    put :update_restaurants
  end

  resources :balances, only: :index
end

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      = link_to 'Where to eat?!', root_path, class: 'navbar-brand'
    #navigation.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: ('active' if params[:controller] == 'restaurants')}
          = link_to 'Restaurants', restaurants_path
        %li{class: ('active' if params[:controller] == 'votes')}
          = link_to 'Votes', votes_path
        %li{class: ('active' if params[:controller] == 'groups')}
          = link_to current_group.name, group_path
        - if current_user.admin?
          %li{class: ('active' if params[:controller] == 'admin')}
            = link_to 'Admin', rails_admin_path
      .nav.navbar-nav.navbar-right.fork-me
        %a.btn.btn-warning.navbar-btn.btn-xs{href: 'https://github.com/springfield/wheretoeat', target: '_blank'}
          Fork me
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{data: {toggle: 'dropdown'}, aria: {haspopup: 'true'}, role: 'button'}
            = current_user.username
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to 'Settings', settings_path
            %li
              = link_to 'Change password', edit_user_registration_path
            %li
              = link_to 'Logout', destroy_user_session_path, method: :delete