config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root to: 'dashboard#index'
  
  resources :restaurants do
    resources :menus, except: :index
    get 'update_menus', to: 'restaurants#update_menus'
  end
  
  resources :dashboard, only: :index

  resources :comments, only: :create

  resource :votes, only: [:show, :create, :destroy]

  resources :votes do
    resources :comments, only: [:new, :edit, :create, :update]
  end

  resources :settings, only: [:index, :create]

  resource :group, only: [:show, :update] do
    post :add_user
    put :update_restaurants
  end

  resources :balances, only: :index
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :menus
  has_many :votes
  has_many :images

  MENU_PARSERS = %w( kamjest strike )

  def grouped_menus
    menus_array = []
    for date in Date.today..4.days.from_now
      menus_array << {date: date, menus: menus.where('date=? OR regular=true', date).order(:regular)}
    end
    menus_array
  end

  def todays_menus
    @todays_menus ||= menus.where('date=? OR regular=true', Date.today).order(:regular)
  end

  def todays_images
    @todays_images ||= images.where date: Date.today
  end

  def today_votes_number(user)
    @no_of_votes ||= votes.where(date: Date.today, group: user.group).count
  end

  def voters(user)
    @voters ||= votes.where(date: Date.today, group: user.group).map do |vote|
      vote.user
    end
  end

  def update_menus
    return false unless menu_parser.present?
    begin
      instance_eval(menu_parser).each do |day|
        menus.where(date: day[:date]).destroy_all
        menus << day[:menus].map{ |m| Menu.new(m) }
        images.where(date: day[:date]).destroy_all
        images << day[:images].map{ |i| Image.new(i) }
      end
      true
    rescue
      false
    end
  end

  def menu_parser_enum
    MENU_PARSERS
  end

  rails_admin do
    create do
      field :kamjest_id do
        label 'Kam jest ID'
      end
      include_all_fields
      exclude_fields :votes, :menus
    end

    edit do
      field :kamjest_id do
        label 'Kam jest ID'
      end
      include_all_fields
      exclude_fields :votes, :menus
    end
  end

  private

  def kamjest
    KamjestCommunicator.get_menus(kamjest_id)
  end

  def strike
    StrikeParser.get_menus
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :admin?, except: [:index, :show]

  def index
    @restaurants = Restaurant.order :name
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    restaurant = Restaurant.new restaurant_params
    restaurant.save
    redirect_to restaurants_path
  end

  def show
    @restaurant = Restaurant.find params[:id]
  end

  def edit
    @restaurant = Restaurant.find params[:id]
  end

  def update
    restaurant = Restaurant.find params[:id]
    restaurant.update restaurant_params
    restaurant.save
    redirect_to restaurants_path
  end

  def destroy
    Restaurant.find(params[:id]).destroy
    redirect_to restaurants_path
  end

  def update_menus
    if Restaurant.find(params[:restaurant_id]).update_menus
      render json: {status: 'success'}, status: 200
    else
      render json: {status: 'failed'}, status: 500
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :default_price, :telephone_number, :menu_link, :menu_parser, :kamjest_id)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_restaurant.html.haml
%tr
  %td.col-md-10
    = link_to restaurant.name, restaurant_path(restaurant)
  %td.text-right
    = restaurant.default_price
  %td.text-right
    - if restaurant.menu_parser.present?
      = link_to restaurant_update_menus_path(restaurant), class: 'refresh_menus' do
        %i.fa.fa-refresh
    - if current_user.admin?
      = link_to edit_restaurant_path(restaurant) do
        %span.glyphicon.glyphicon-pencil
      = link_to restaurant_path(restaurant), method: :delete, data: {confirm: 'Are you sure?'} do
        %span.glyphicon.glyphicon-remove.text-danger

app/views/restaurants/edit.html.haml
.row
  .col-md-4.col-md-offset-4
    = form_for @restaurant, url: {action: 'update'} do |f|
      .form-group
        = f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Name'
      .form-group
        .input-group
          .input-group-addon
            %span.glyphicon.glyphicon-euro
          = f.number_field :default_price, class: 'form-control', step: 'any'
      .form-group
        = f.text_field :telephone_number, class: 'form-control', placeholder: '555-1234'
      .form-group
        = f.url_field :menu_link, class: 'form-control', placeholder: 'http://menu.link'
      .form-group
        = f.select :menu_parser, Restaurant::MENU_PARSERS, { include_blank: 'Menu parser' }, { class: 'form-control' }
      .form-group
        =f.text_field :kamjest_id, class: 'form-control', placeholder: 'Kam jest id'
      = f.submit "Save", class: 'btn btn-success'
      = link_to 'Back', restaurants_path, class: 'btn btn-danger'

app/views/restaurants/index.html.haml
%table.table.table-hover
  %tr
    %th
      Name
    %th.text-right
      Default price
    %th.text-right
      Actions
      = link_to restaurants_path, class: 'refresh_all_menus', title: 'Refresh all' do
        %i.fa.fa-refresh
  = render @restaurants
- if current_user.admin?
  = link_to 'Add', new_restaurant_path, class: 'btn btn-success'

app/views/restaurants/new.html.haml
.row
  .col-md-4.col-md-offset-4
    = form_for @restaurant, url: {action: 'create'} do |f|
      .form-group
        = f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Name'
      .form-group
        .input-group
          .input-group-addon
            %span.glyphicon.glyphicon-euro
          = f.number_field :default_price, class: 'form-control', value: 5, step: 'any'
      .form-group
        = f.text_field :telephone_number, class: 'form-control', placeholder: '555-1234'
      .form-group
        = f.url_field :menu_link, class: 'form-control', placeholder: 'http://menu.link'
      .form-group
        = f.select :menu_parser, Restaurant::MENU_PARSERS, { include_blank: 'Menu parser' }, { class: 'form-control' }
      .form-group
        = f.text_field :kamjest_id, class: 'form-control', placeholder: 'Kam jest id'
      = f.submit "Save", class: 'btn btn-success'
      = link_to 'Back', restaurants_path, class: 'btn btn-danger'

app/views/restaurants/show.html.haml
%h3
  = @restaurant.name
- if @restaurant.menu_parser.present?
  = link_to restaurant_update_menus_path(@restaurant), class: 'refresh_menus', title: 'Refresh menus' do
    %i.fa.fa-refresh
  |
= link_to 'Menus', @restaurant.menu_link, target: '_blank' if @restaurant.menu_link.present?
- if @restaurant.kamjest_id.present?
  |
  = link_to 'Data', "http://kam-jest.herokuapp.com/graphql?query=%7B%0A%20%20restaurants(id%3A%22#{@restaurant.kamjest_id}%22)%7B%0A%20%20%20%20name%0A%20%20%20%20dailyOffers(date%3A%22#{Date.today}%22)%7B%0A%20%20%20%20%20%20date%0A%20%20%20%20%20%20offersImages%0A%20%20%20%20%20%20offers%20%7B%0A%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%20%20type%0A%20%20%20%20%20%20%20%20price%0A%20%20%20%20%20%20%20%20allergens%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D", target: '_blank'
- @restaurant.grouped_menus.each_slice(4) do |menus|
  .row
    - menus.each do |menu_object|
      .col-md-3
        .panel.panel-default
          .panel-heading
            %h3.panel-title= menu_object[:date].strftime("%e.%-m.%Y")
          .fixed-height
            %table.table.table-hover
              - if menu_object[:menus].empty?
                %tr
                  %td.text-center
                    No data
              - else
                - menu_object[:menus].each_with_index do |menu, i|
                  %tr{class: ('info' if menu.regular?)}
                    %td.col-md-1.text-left= i + 1
                    %td.col-md-8.text-left= menu.description
                    %td.col-md-1.text-right= "#{menu.price}€"
                    - if current_user.admin?
                      %td.col-md-2.text-right
                        = link_to edit_restaurant_menu_path(menu.restaurant_id, menu.id) do
                          %span.glyphicon.glyphicon-pencil
                        = link_to restaurant_menu_path(menu.restaurant_id, menu.id), method: :delete, data: {confirm: 'Are you sure?'} do
                          %span.glyphicon.glyphicon-remove.text-danger
          - if current_user.admin?
            .panel-footer
              = link_to 'Add menu', new_restaurant_menu_path(@restaurant, date: menu_object[:date]), class: 'btn btn-success'